### PR TITLE
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### LINKED ISSUE #102: No longer works for Angular 13
**Describe the bug**
After upgrading to Angular 13, ng deploy no longer works. I get the following error
`An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID"`

**To Reproduce**
1. Generate a new angular using version 13
2. Add @azure/ng-deploy
3. Configure
4. Run ng deploy

**Expected behavior**
Deploy should be successful

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 0.2.3

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by doggy8088**
This PR fixes #102

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

**Review by manekinekko — APPROVED** [review]

**Review by manekinekko — APPROVED** [review]

**Comment by doggy8088** [comment]
@manekinekko Will you publish to [npm registry](https://www.npmjs.com/package/@azure/ng-deploy)? I see [@azure/ng-deploy](https://www.npmjs.com/package/@azure/ng-deploy) is not updated since 3 years ago.

**Comment by manekinekko** [comment]
I am sorry about the inconvenience. I don't have any ETA for that. Our DevOps team is looking at how to streamline our internal deployment process to npm. Will keep you posted. Thank you.

**Comment by doggy8088** [comment]
@manekinekko 
This PR seems not solving the issue. I still can reproduce the same error with the latest version of Azure CLI. I'm still looking for a solution.

**Comment by doggy8088** [comment]
@manekinekko 
I finally solved the puzzle. The `@angular-devkit/*` is outdated and it's not compatible with latest Angular CLI Builders.

**Pull request merged**
