### PR TITLE
Update libs

### LINKED ISSUE #102: No longer works for Angular 13
**Describe the bug**
After upgrading to Angular 13, ng deploy no longer works. I get the following error
`An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID"`

**To Reproduce**
1. Generate a new angular using version 13
2. Add @azure/ng-deploy
3. Configure
4. Run ng deploy

**Expected behavior**
Deploy should be successful

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 0.2.3

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by shmool**
# Pull Request Template

## Description

Angular V13 introduced a breaking change which made the ng-deploy-azure schematics fail. 
In addition, the Angular schematics libraries were updated with breaking changes.
This PR updates the code to run with Angular 13 projects.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How to Test

Create an Angular project with version 13. Then add ng-deploy-azure as instructed. 
The run should be successful.

## Closing issues

Closes #102

## Assignee
@shmool

### CODE REVIEW

**Review by sinedied — APPROVED** [review]
LGTM 👍

**Comment by fhinkel** [comment]
Thanks, Please don't merge this until we have a recent CI run on master so we can compare before and after.

**Comment by stuartst** [comment]
Can we get this reviewed and committed please?

**Comment by manekinekko** [comment]
This PR was merged manually in e4bca173373da66b92de9103fd4da0f132144f0f to 2149211ff761b5a3705f43addcc39a12a836c787

**Pull request closed without merging**
